### ISSUE TITLE
Slow cropping to 1:1 aspect ratio

### ISSUE THREAD

**Issue by buntupana** [deepmedia/Transcoder#79] opened 2020-04-17 22:30 UTC
I'm cropping a 90 seconds video with 1920*1080 resolution to a 1080*1080 video. It takes 50 seconds, is there any way to boost this?

This is the code I'm using:

```
        val strategy = DefaultVideoStrategy.Builder()
            .addResizer(AspectRatioResizer(1F / 1F)).build()

        Transcoder.into(videoName)
            .setVideoTrackStrategy(strategy)
            .setListener(listener)
            .addDataSource(sourcePath)
            .transcode()
```

**Comment by natario1** [comment] 2024-08-11 16:16
Duplicate of #71

**Closed by natario1** 2024-08-11 16:16 UTC
