### ISSUE TITLE
Fatal error while transcoding, this might be invalid format or bug in engine or Android.

### ISSUE THREAD

**Issue by bhaveshjethani** [deepmedia/Transcoder#96] opened 2020-07-27 14:35 UTC
E/MediaCodec: Codec reported err 0xffffec77, actionCode 0, while in state 3

E/MediaCodec: configure failed with err 0xffffec77, resetting...

E/Transcoder: Fatal error while transcoding, this might be invalid format or bug in engine or Android.
    android.media.MediaCodec$CodecException: Error 0xffffec77
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:1960)
        at android.media.MediaCodec.configure(MediaCodec.java:1889)
        at com.otaliastudios.transcoder.transcode.VideoTrackTranscoder.onConfigureDecoder(VideoTrackTranscoder.java:105)
        at com.otaliastudios.transcoder.transcode.BaseTrackTranscoder.setUp(BaseTrackTranscoder.java:75)
        at com.otaliastudios.transcoder.engine.Engine.openCurrentStep(Engine.java:194)
        at com.otaliastudios.transcoder.engine.Engine.getCurrentTrackTranscoder(Engine.java:223)
        at com.otaliastudios.transcoder.engine.Engine.transcode(Engine.java:371)
        at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:150)
        at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:140)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
 E/Transcode Failed: Error 0xffffec77

### Device: Samsung J8
OS: 9 Pie
**If video is below 10 seconds then it get compressed.**
if (video is portrait)
atMost =540
else
atMost = 304

val strategy = DefaultVideoStrategy.Builder()
                .addResizer(AtMostResizer(atMost))
                .bitRate(1700000)
                .frameRate(30)
                .build()

Transcoder.into("output Path")
                .addDataSource("input path")
                .setVideoTrackStrategy(strategy)
                .setListener(this).transcode()

**Comment by charlieaboumoussa** [comment] 2020-11-08 18:32
@bhaveshjethani Same. Any Update?

**Comment by bhaveshjethani** [comment] 2020-11-09 07:45
Add some delay before starting compress process! like 500 milliseconds.

**Comment by halilozdemr** [comment] 2020-11-18 11:01
> Add some delay before starting compress process! like 500 milliseconds.

I am getting same error. and delay didn't work.

**Comment by halilozdemr** [comment] 2020-11-23 09:15
In my case, Transcoder and ExoPlayer were running at the same time. When I play ExoPlayer after the Transcoder is complete, my problem was resolved. I think the problem is caused by them using the MediaCodec class at the same time.

**Comment by pawan972019** [comment] 2021-06-10 07:13
Transcoder ver - 0.9.1
I am facing this issue in android 11 devices while merging two or more video else below android 11 video merging works fine. 

Fatal error while transcoding, this might be invalid format or bug in engine or Android.
    java.lang.IllegalStateException: writeSampleData returned an error
        at android.media.MediaMuxer.nativeWriteSampleData(Native Method)
        at android.media.MediaMuxer.writeSampleData(MediaMuxer.java:722)
        at com.otaliastudios.transcoder.sink.DefaultDataSink.writeTrack(DefaultDataSink.java:151)
        at com.otaliastudios.transcoder.transcode.BaseTrackTranscoder.drainEncoder(BaseTrackTranscoder.java:288)
        at com.otaliastudios.transcoder.transcode.BaseTrackTranscoder.transcode(BaseTrackTranscoder.java:163)
        at com.otaliastudios.transcoder.engine.Engine.transcode(Engine.java:373)
        at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:150)
        at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:140)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)


if i am updating the transcoder lib to 0.10.3 then video compression is not working.

**Comment by rishabhOpenxcell** [comment] 2022-03-04 06:50
tempDir = await getTemporaryDirectory();

file = await File(tempDir.path+'Vid${DateTime.now().millisecondsSinceEpoch}.mp4').writeAsBytes(File(updatedPath).readAsBytesSync());

 mediaInfo = await VideoCompress.compressVideo(
            file.path,
            quality: VideoQuality.Res960x540Quality,
            deleteOrigin: false,
          );

just make a temporary file in cache directory and then give its path in compress.
it will work!!

**Comment by dode2121** [comment] 2022-03-05 12:01
Any update on this issue?

**Comment by NikolaDespotoski** [comment] 2023-01-27 22:55
I don't know if it is same issue however, I was parallelizing multiple conversion at the same time. I made the conversion in serial fashion the issue is gone. It was a problem primarily on huawei devices.

**Comment by natario1** [comment] 2024-08-11 17:22
(Pasted to all my answers today: it's been a long time since my last issues review. I am sorry about the delay and I know you likely have moved on by now. Still, I'm going to answer where I can)

I'm closing this as too vague to be actionable. The error string doesn't say much. For some of you, it was a problem of concurrent encoders/decoders. For others, I would need to have sample videos so I can reproduce the problem on my own.

**Closed by natario1** 2024-08-11 17:22 UTC
