### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke interface method 'boolean com.otaliastudios.transcoder.source.DataSource.isInitialized()' on a null object reference

### ISSUE THREAD

**Issue by Kanishk251296** [deepmedia/Transcoder#177] opened 2022-07-31 12:16 UTC
```
String srcPath = "/storage/emulated/0/Download/sample.mp3";
String desPath = "/storage/emulated/0/Download/hmm.aac";
            Log.e(TAG, "onActivityResult: "+srcPath);
            DefaultAudioStrategy strategy = DefaultAudioStrategy.builder()
                    .channels(DefaultAudioStrategy.CHANNELS_AS_INPUT)
                    .channels(1)
                    .channels(2)
                    .sampleRate(DefaultAudioStrategy.SAMPLE_RATE_AS_INPUT)
                    .sampleRate(44100)
                    .sampleRate(30000)
                    .bitRate(DefaultAudioStrategy.BITRATE_UNKNOWN)
                    .build();
            Transcoder.into(desPath)
                    .addDataSource(srcPath)
                    .setAudioTrackStrategy(strategy)
                    .setListener(new TranscoderListener() {
                        @Override
                        public void onTranscodeProgress(double progress) {
                            Log.e(TAG, "onTranscodeProgress: ");
                        }

                        @Override
                        public void onTranscodeCompleted(int successCode) {
                            Log.e(TAG, "onTranscodeCompleted: ");
                        }

                        @Override
                        public void onTranscodeCanceled() {
                            Log.e(TAG, "onTranscodeCanceled: ");
                        }

                        @Override
                        public void onTranscodeFailed(@NonNull Throwable exception) {
                            Log.e(TAG, "onTranscodeFailed: "+exception);
                        }
                    }).transcode();
```
                    
     Whenever i a running this code i am getting this error
     
     
     **
2022-07-31 17:39:10.337 10749-10822/com.example.transcoder I/TranscodeEngine: transcode(): called...
2022-07-31 17:39:10.338 10749-10822/com.example.transcoder I/DataSources: initializing videoSources...
2022-07-31 17:39:10.338 10749-10822/com.example.transcoder E/TranscodeEngine: Unexpected error while transcoding.
    java.lang.NullPointerException: Attempt to invoke interface method 'boolean com.otaliastudios.transcoder.source.DataSource.isInitialized()' on a null object reference
        at com.otaliastudios.transcoder.source.DataSourceWrapper.isInitialized(DataSourceWrapper.java:99)
        at com.otaliastudios.transcoder.internal.DataSources.init(DataSources.kt:25)
        at com.otaliastudios.transcoder.internal.DataSources.<init>(DataSources.kt:35)
        at com.otaliastudios.transcoder.internal.DataSources.<init>(DataSources.kt:17)
        at com.otaliastudios.transcoder.internal.transcode.TranscodeEngine$Companion.transcode(TranscodeEngine.kt:33)
        at com.otaliastudios.transcoder.internal.transcode.TranscodeEngine.transcode(Unknown Source:2)
        at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:102)
        at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:99)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:920)
2022-07-31 17:39:10.340 10749-10749/com.example.transcoder E/ContentValues: onTranscodeFailed: java.lang.NullPointerException: Attempt to invoke interface method 'boolean com.otaliastudios.transcoder.source.DataSource.isInitialized()' on a null object reference
2022-07-31 17:39:10.394 10749-10749/com.example.transcoder V/ImeFocusController: onWindowFocus: DecorView@56cf556[MainActivity] softInputMode=STATE_UNSPECIFIED|ADJUST_PAN**

**Comment by Deepfreezed** [comment] 2022-08-09 20:25
I am also getting this error. Anyone knows what the issue is?

**Comment by Kanishk251296** [comment] 2022-08-10 05:52
> I am also getting this error when using .addDataSource(srcPath).
> 
> Although, this is working .addDataSource(context, uri).

Actually i have tried that also
i am still getting the same error

**Comment by tfidmmatthew** [comment] 2022-11-28 04:37
How did you fix it?

**Comment by natario1** [comment] 2024-08-11 16:54
(Pasted to all my answers today: it's been a long time since my last issues review. I am sorry about the delay and I know you likely have moved on by now. Still, I'm going to answer where I can)

Looking at the current code I don't see how this can happen anymore, so I'm closing this. Feel free to add more info.

**Closed by natario1** 2024-08-11 16:54 UTC
