### ISSUE TITLE
[Bug]Sometimes the compressed video file would be corrupted.

### ISSUE THREAD

**Issue by sbs-surendhar-kabilan** [deepmedia/Transcoder#173] opened 2022-03-03 08:12 UTC
We are using OtaliaStudios.TranscoderLib ITranscoderListener to compress the video in our application. 

Current behavior:
Sometimes the compressed video file would be corrupted and getting exceptions in our application.

Expected behavior:
After compressing the video, the video should be playable and not corrupt.

In our application, please see the code snippet that we were used for compressing the video. 

VideoTranscoder.TranscodeVideoAsync(inputPath, outputPath);

 public static async Task<string> TranscodeVideoAsync(string sourceVideoPath, string outputpath)
 {

            string path = System.IO.Path.GetDirectoryName(outputpath);
            AVAssetExportSession export = new AVAssetExportSession(sourceVideoPath);
            string outputFilePath = Path.Combine(path, $"{DateTime.Now.ToString(DateString.strDMYHMS, AppState.CultureInfo)}.mp4");
            export.OutputPath = outputFilePath;

            await export.ExportTaskAsync();

            MemoryStream output = new MemoryStream();
            using (Stream source = File.OpenRead(outputFilePath))
                await source.CopyToAsync(output);

            output.Seek(0, SeekOrigin.Begin);
            return outputFilePath;
}

 public async Task ExportTaskAsync()
 {

                 DefaultVideoStrategy videoStrategy = new DefaultVideoStrategy.Builder()
                    .AddResizer(new ExactResizer(720, 1280))
                    .BitRate(4096)
                    .FrameRate(40)
                    .KeyFrameInterval(3f)
                    .Build();

                DefaultAudioStrategy audioStrategy = new DefaultAudioStrategy.Builder()
                       .SampleRate(DefaultAudioStrategy.SampleRateAsInput)
                 .BitRate(DefaultAudioStrategy.BitrateUnknown).Build();

                await _semaphore.WaitAsync();
                Transcoder.Into(this.OutputPath)
                    .AddDataSource(_assetPath)
                    .SetVideoTrackStrategy(DefaultVideoStrategies.For720x1280())
                    .SetAudioTrackStrategy(audioStrategy)
                    .SetListener(this)
                    .Transcode();
                await _semaphore.WaitAsync();
}

**Comment by natario1** [comment] 2024-08-11 17:55
(Pasted to all my answers today: it's been a long time since my last issues review. I am sorry about the delay and I know you likely have moved on by now. Still, I'm going to answer where I can)

Unfortunately I should have the actual video files that reproduce the issue in order to understand what's wrong. Closing it for now.

**Closed by natario1** 2024-08-11 17:55 UTC
